name: souqalgomlah_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+16

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.2.0
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dropdown_search: ^5.0.6
  easy_loading_button: ^0.3.2
  easy_localization: ^3.0.5
  easy_localization_loader: ^2.0.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_feather_icons: ^2.0.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_otp_text_field: ^1.1.3+2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: ^7.7.0
  intl: any
  lottie: ^3.1.0
  pretty_dio_logger: ^1.3.1
  rename: ^3.0.2
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.1.2
  device_preview: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # url laucnher
  url_launcher: ^6.3.0
  confetti: ^0.7.0
  webview_flutter: ^3.0.4
  email_validator: ^3.0.0
  package_info_plus: ^8.0.2
  connectivity_plus: ^6.0.5
  avatar_glow: ^3.0.1

# Launcher Icon Configurations
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/launcher_icon.png"

# Splash Screen Configurations
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"
  android: true
  ios: true
  web: true

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  
  hive_generator: ^2.0.1
  build_runner: ^2.0.6

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/anim/
    - assets/translations/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
